# Fake News Classifier


In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
df=  pd.read_csv("./dataset/train.csv")
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [3]:
df.isna().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [4]:
df=df.dropna()

In [5]:
# df.reset_index(inplace=True) # reset index

In [6]:
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[18285 rows x 5 columns]

In [7]:
X= df.drop('label', axis=1)

In [8]:
Y = df['label']

In [9]:
X.shape

(18285, 4)

In [10]:
Y.shape

(18285,)

In [11]:
import tensorflow as tf

In [12]:
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot

In [13]:
vocab_size = 5000

In [14]:
msg = X.copy()
msg.reset_index(drop=True, inplace=True)

In [15]:
import nltk
import re
from nltk.corpus import stopwords

In [16]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\basav\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [17]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()
corpus = []

for i in range(len(msg)):
    review = re.sub('[^a-zA-Z]', ' ', msg['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    
    corpus.append(review)

In [18]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [19]:
onehot_rep = [one_hot(word, vocab_size) for word in corpus]

In [20]:
onehot_rep

[[3323, 3248, 3251, 1016, 2901, 3676, 2962, 580, 1321, 436],
 [579, 3259, 4054, 3718, 2899, 1412, 4816],
 [2872, 2178, 1570, 4849],
 [1117, 1710, 1072, 4953, 3133, 3669],
 [152, 2899, 2653, 1188, 2234, 4898, 2899, 4474, 1191, 1314],
 [2854,
  4999,
  4090,
  1260,
  4898,
  1964,
  1546,
  97,
  152,
  1543,
  1886,
  4465,
  1652,
  1529,
  4816],
 [302, 3024, 4481, 4859, 4528, 2134, 563, 1595, 808, 2374, 2261],
 [1785, 2589, 1835, 4767, 2807, 1434, 1964, 3564, 808, 2374, 2261],
 [2194, 1208, 3769, 2907, 4633, 3753, 447, 3392, 1964, 712],
 [2725, 676, 3413, 772, 63, 1999, 1834, 4144],
 [1341, 3000, 1662, 3004, 4254, 4100, 4437, 809, 4857, 4572, 3862],
 [4953, 378, 2901, 3753, 1964, 2807],
 [2749, 4829, 166, 2851, 1731, 427, 812, 1245, 3344],
 [827, 2117, 1867, 1157, 2817, 3546, 3263, 808, 2374, 2261],
 [3532, 1187, 2014, 3847, 1062, 808, 2374, 2261],
 [3481, 2560, 1577, 3794, 3570, 3317, 1161, 290, 3610, 1744],
 [3466, 4866, 3259],
 [4706, 4739, 2226, 2895, 1964, 2993, 1763, 4816],
 [

In [21]:
sent_len = 20

embedding_doc = pad_sequences(onehot_rep, maxlen=sent_len, padding='pre')


In [22]:
embedding_doc

array([[   0,    0,    0, ...,  580, 1321,  436],
       [   0,    0,    0, ..., 2899, 1412, 4816],
       [   0,    0,    0, ..., 2178, 1570, 4849],
       ...,
       [   0,    0,    0, ...,  808, 2374, 2261],
       [   0,    0,    0, ..., 4242, 3632, 2990],
       [   0,    0,    0, ..., 2802, 4506, 2737]])

In [24]:
embeding_vector_length = 40

model = Sequential()
model.add(Embedding(vocab_size, embeding_vector_length, input_length=sent_len))
model.add(LSTM(100))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [26]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [32]:
import numpy as np

X= np.array(embedding_doc)
y= np.array(Y)

In [33]:
X.shape

(18285, 20)

In [34]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=.33)

In [35]:
model.fit(X_train, y_train, epochs=10, batch_size=64, validation_data=(X_test, y_test))

Epoch 1/10
192/192 [==============================] - 6s 10ms/step - loss: 0.3332 - accuracy: 0.8455 - val_loss: 0.1940 - val_accuracy: 0.9193
Epoch 2/10
192/192 [==============================] - 2s 9ms/step - loss: 0.1389 - accuracy: 0.9452 - val_loss: 0.2216 - val_accuracy: 0.9196
Epoch 3/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0946 - accuracy: 0.9647 - val_loss: 0.2406 - val_accuracy: 0.9196
Epoch 4/10
192/192 [==============================] - 2s 8ms/step - loss: 0.0643 - accuracy: 0.9792 - val_loss: 0.2687 - val_accuracy: 0.9153
Epoch 5/10
192/192 [==============================] - 1s 8ms/step - loss: 0.0369 - accuracy: 0.9886 - val_loss: 0.2920 - val_accuracy: 0.9042
Epoch 6/10
192/192 [==============================] - 1s 8ms/step - loss: 0.0249 - accuracy: 0.9924 - val_loss: 0.3406 - val_accuracy: 0.9142
Epoch 7/10
192/192 [==============================] - 1s 8ms/step - loss: 0.0131 - accuracy: 0.9958 - val_loss: 0.4267 - val_accuracy: 0.9125
Epoch

In [36]:
model.save('model_title.h5')

In [42]:
y_pred = model.predict(X_test)

189/189 [==============================] - 1s 3ms/step


In [41]:
y_test

array([1, 0, 0, ..., 0, 1, 1], dtype=int64)

In [44]:
y_pred = [0 if x < 0.5 else 1 for x in y_pred]

In [45]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[3113,  306],
       [ 223, 2393]], dtype=int64)

In [46]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.9123446561723281